<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory Home Gutenverse About', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-Tivv1W","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"960"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"80"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"80"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"40"}},"background":{"type":"default","image":{"Desktop":{"id":16,"image":"{image|other|7|url}","width":60,"height":60,"altOriginal":""}},"position":{"Desktop":"center center"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"40"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 0.88)","active":false,"opacity":0.88,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 1)","opacity":1,"active":true,"id":2,"offset":"0.685"}],"gradientType":"radial"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"24","left":"24","top":""}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-9qB3X2","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"604"}},"minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInDown"}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-OfHhXG","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eWe dedicated to bring IT solutions for your business\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"size":{"Desktop":{"unit":"px","point":"48"}},"spacing":{"Desktop":"-0.02"},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-neRaIL","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"containsAnchorTag":false,"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-UCMtjV","paragraph":"With over a decade of experience across industries, we partner with companies to build smart, resilient, and future-ready digital systems.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"494"},"Mobile":{"unit":"px"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-UQ42qf","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"flexDirection":{"Desktop":"row","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"96","left":"96"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-sHCxna","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-hLC7iO","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-NNF6nV","displayInline":true,"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-P4vIK5","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Our Vision"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-43KPLE","content":"IT Solutions","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-c3SEQd","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-jtfMmo","paragraph":"To be the most trusted technology advisory partner for businesses navigating digital change - empowering every client to harness technology as a true competitive advantage.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/image {"elementId":"guten-IVu0YH","imgSrc":{"media":{"imageId":"21","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|21|url}","orientation":"landscape"},"medium":{"height":131,"width":300,"url":"{image|other|21|url}","orientation":"landscape"},"full":{"url":"{image|other|21|url}","height":288,"width":660,"orientation":"landscape"}}},"size":"full","id":"{image|case1|21|id}","image":"{image|case1|21|url}"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"240"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"imageFit":{"Desktop":"cover"},"mask":{"shape":"custom","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"}},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-7iEaHr","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInRight"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-xkcYp0","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-QGj6iF","displayInline":true,"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-VHG5Y9","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Our Mission"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-lhsUx4","content":"Real Results","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-hw3841","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-vlJ0b3","paragraph":"To deliver strategic, honest, and results-driven IT consulting that aligns with our clients goals - delivering clarity, capability, and measurable outcomes at every engagement.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/image {"elementId":"guten-gvXmni","imgSrc":{"media":{"imageId":"22","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|22|url}","orientation":"landscape"},"medium":{"height":131,"width":300,"url":"{image|other|22|url}","orientation":"landscape"},"full":{"url":"{image|other|22|url}","height":288,"width":660,"orientation":"landscape"}}},"size":"full","id":"{image|case1|22|id}","image":"{image|case1|22|url}"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"240"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}},"imageFit":{"Desktop":"cover"},"mask":{"shape":"custom","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center"}},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-iBOxL4","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"716"}},"minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-hhidUA","space":{"Desktop":{"unit":"px","point":"32"}},"zIndex":{"Desktop":2},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"64"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"px","point":"0"}},"positioningRight":{"Desktop":{"unit":"px"}},"positioningTop":{"Desktop":{"unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px"}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"}} /-->

<!-- wp:gutenverse/logo-slider {"elementId":"guten-KwklqW","logos":[{"title":"One","imageLoad":"lazy","_key":"RHl8lw","src":{"id":113,"image":"{image|other|37|url}","width":198,"height":39,"altOriginal":""}},{"title":"Two","imageLoad":"lazy","_key":"AttADA","src":{"id":114,"image":"{image|other|38|url}","width":164,"height":39,"altOriginal":""}},{"title":"Three","imageLoad":"lazy","_key":"qxSuei","src":{"id":115,"image":"{image|other|39|url}","width":173,"height":39,"altOriginal":""}},{"title":"Four","imageLoad":"lazy","_key":"xr4m06","src":{"id":112,"image":"{image|other|40|url}","width":183,"height":39,"altOriginal":""}}],"imageFixHeight":true,"imageHeight":{"Desktop":"32"},"imageFit":{"Desktop":"contain"},"transitionDuration":{"Desktop":"0"},"spacing":{"Desktop":"40"},"itemShowed":{"Desktop":"4","Tablet":"4","Mobile":"3"},"opacity":"0.16","hoverOpacity":"0.16","logoWrapperMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"logoWrapperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/spacer {"elementId":"guten-rQzgpK","space":{"Desktop":{"unit":"px","point":"32"}},"zIndex":{"Desktop":2},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"64"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"px"}},"positioningRight":{"Desktop":{"unit":"px","point":"0"}},"positioningTop":{"Desktop":{"unit":"px"}},"positioningBottom":{"Desktop":{"unit":"px"}},"background":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"-90"}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '{"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/our-team-vision.webp":{"pattern":["{image|case1|21|url}","{image|case1|21|id}","{image|other|21|url}"],"alt_text":"our team vision"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/our-team-mission.webp":{"pattern":["{image|case1|22|url}","{image|case1|22|id}","{image|other|22|url}"],"alt_text":"our team mission"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/pattern-diamond-dot.webp":{"pattern":["{image|other|7|url}"]},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-gradient-masking.svg":{"pattern":["{image|other|36|url}"]},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-client-logo-1.webp":{"pattern":["{image|other|37|url}"]},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-client-logo-2.webp":{"pattern":["{image|other|38|url}"]},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-client-logo-3.webp":{"pattern":["{image|other|39|url}"]},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-client-logo-4.webp":{"pattern":["{image|other|40|url}"]}}',
	'is_sync' => false,
);
