<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory About Gutenverse Team', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-r22r57","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"80"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"24","bottom":"160","left":"24"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-Egtzq2","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"551"}},"backgroundEffect":{"type":"none","leftOrientation":{"Desktop":{"unit":"%"}},"topOrientation":{"Desktop":{"unit":"%"}},"effectSpeed":{"unit":"s","point":""},"backgroundEffectSize":{"Desktop":{"unit":"px","point":""}},"backgroundEffectLoadOn":"pageLoad","effectColor":{"type":"variable","id":"gv-color-white"},"opacity":{"Desktop":""},"effectQuantity":""}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-6msxDO","displayInline":true,"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"center"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-UWatCo","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Team"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-8SQXpY","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eOur Expertise\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-primary-alt","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-3Rqlhi","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"flexDirection":{"Desktop":"row","Tablet":"row"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"flexWrap":{"Desktop":"wrap"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-dePrpq","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"}},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-NszOVF","imgSrc":{"media":{"imageId":"15","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|15|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|15|url}","orientation":"landscape"},"full":{"url":"{image|other|15|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|15|id}","image":"{image|case1|15|url}"},"altType":"original","altOriginal":"tecvisory team member 01","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-AJgA52","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-bouV0f","content":"Raymond Hills","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-EqiN3J","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-GjaUbV","paragraph":"Founder \u0026 CEO","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-g7oMZL","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":100},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-rNpnZx","imgSrc":{"media":{"imageId":"16","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|16|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|16|url}","orientation":"landscape"},"full":{"url":"{image|other|16|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|16|id}","image":"{image|case1|16|url}"},"altType":"original","altOriginal":"tecvisory team member 02","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-SbSSbX","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-LJYq7l","content":"Amalia Seeds","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-1smwh4","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-Fh5cng","paragraph":"Chief Technology Officer","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-4Glly1","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":200},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-2CYXeE","imgSrc":{"media":{"imageId":"17","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|17|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|17|url}","orientation":"landscape"},"full":{"url":"{image|other|17|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|17|id}","image":"{image|case1|17|url}"},"altType":"original","altOriginal":"tecvisory team member 03","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-nIDy1h","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-M0dW0T","content":"Daniel Parker","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-F3pmfP","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-vDIRGX","paragraph":"Head of Cybersecurity","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-S2GpTD","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"}},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-ZavTdO","imgSrc":{"media":{"imageId":"18","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|18|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|18|url}","orientation":"landscape"},"full":{"url":"{image|other|18|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|18|id}","image":"{image|case1|18|url}"},"altType":"original","altOriginal":"tecvisory team member 04","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-7Frgsx","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-AoNyvI","content":"Nadya Amanda","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-CrPtel","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-bNXA6C","paragraph":"Digital Transformation Lead","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-2KWnhZ","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":100},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-HUX6io","imgSrc":{"media":{"imageId":"19","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|19|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|19|url}","orientation":"landscape"},"full":{"url":"{image|other|19|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|19|id}","image":"{image|case1|19|url}"},"altType":"original","altOriginal":"tecvisory team member 05","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-YNec7f","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-ErzIJL","content":"Marcus Brown","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3Sp6Rr","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-PePlA9","paragraph":"Senior IT Strategist","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-MryKGW","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"delay":200},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"28"},"Tablet":{"unit":"%","point":"47"},"Mobile":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-DiMTQ7","imgSrc":{"media":{"imageId":"20","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|20|url}","orientation":"landscape"},"medium":{"height":300,"width":300,"url":"{image|other|20|url}","orientation":"landscape"},"full":{"url":"{image|other|20|url}","height":414,"width":414,"orientation":"landscape"}}},"size":"full","id":"{image|case1|20|id}","image":"{image|case1|20|url}"},"altType":"original","altOriginal":"tecvisory team member 06","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"345"},"Mobile":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"mask":{"shape":"","svg":{"id":105,"image":"{image|other|36|url}","altOriginal":""},"size":{"Desktop":"cover","Mobile":"cover"},"position":{"Desktop":"bottom center","Mobile":"top center"},"repeat":{"Desktop":"no-repeat"},"scale":{"Desktop":{"unit":"px","point":"345"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-krFBhu","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-HjNA88","content":"Laura Ann","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"32"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3XmDkt","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-Z3Hxyh","paragraph":"Client Success Manager","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '{"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-01.webp":{"pattern":["{image|case1|15|url}","{image|case1|15|id}","{image|other|15|url}"],"alt_text":"tecvisory team member 01"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-02.webp":{"pattern":["{image|case1|16|url}","{image|case1|16|id}","{image|other|16|url}"],"alt_text":"tecvisory team member 02"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-03.webp":{"pattern":["{image|case1|17|url}","{image|case1|17|id}","{image|other|17|url}"],"alt_text":"tecvisory team member 03"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-04.webp":{"pattern":["{image|case1|18|url}","{image|case1|18|id}","{image|other|18|url}"],"alt_text":"tecvisory team member 04"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-05.webp":{"pattern":["{image|case1|19|url}","{image|case1|19|id}","{image|other|19|url}"],"alt_text":"tecvisory team member 05"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-team-member-06.webp":{"pattern":["{image|case1|20|url}","{image|case1|20|id}","{image|other|20|url}"],"alt_text":"tecvisory team member 06"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-gradient-masking.svg":{"pattern":["{image|other|36|url}"]}}',
	'is_sync' => false,
);
