<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory FAQ Gutenverse Hero', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-6GpsXM","htmlTag":"section","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"vh","point":""},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row","Tablet":"column"},"justifyContent":{"Desktop":"space-between"},"alignItems":{"Desktop":"flex-end"},"columnGap":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"overflow":"hidden","background":{"type":"default","image":{"Desktop":{"id":16,"image":"{image|other|7|url}","width":60,"height":60,"altOriginal":""}},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"30"}}},"backgroundOverlay":{"type":"gradient","color":{"type":"variable","id":"gv-color-dark-background-primary"},"gradientColor":[{"color":"rgba(26, 26, 26, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 0.9)","active":true,"opacity":0.9,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"1","padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"24","bottom":"40","left":"24"}},"Mobile":{"unit":"px","dimension":{"top":"100"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-iKUm2J","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":""}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-zBCVGv","displayInline":true,"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-primary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-KyCP5d","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"FAQ"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-5it3Lf","content":"\u003cspan id=\u0022guten-B3eeZF\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-ZL9n3F\u0022 id=\u0022guten-wLVG9u\u0022\u003eFrequently Asked Question\u003c/span\u003e\u003c/span\u003e","type":1,"typography":{"type":"variable","id":"gv-font-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"96"}},"weight":"600","spacing":{"Desktop":"-0.02"},"font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"-1","top":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Tablet":"full","Mobile":"full","Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"703"}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-wLVG9u","spanId":"guten-B3eeZF"}],"openChild":"guten-wLVG9u"} /-->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kutUOP","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"containsAnchorTag":false,"positioningType":{"Mobile":"full","Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"420"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-wuYbcG","paragraph":"All your need to know about our IT services and how it works.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"424"},"Mobile":{"unit":"px"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '{"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/pattern-diamond-dot.webp":{"pattern":["{image|other|7|url}"]}}',
	'is_sync' => false,
);
