<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory Gutenverse 404', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-XW6G05","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Mobile":{"unit":"%","point":100},"Tablet":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"vh","point":"100"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"justifyContent":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"80"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"background":{"type":"default","image":{"Desktop":{"id":"7","image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pattern-diamond-dot.webp","width":60,"height":60,"altOriginal":""}},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"40"}},"position":{"Desktop":"bottom center"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 0.8892913783160323)","opacity":0.8892913783160323,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 1)","active":true,"opacity":1,"id":2,"offset":"0.8489999999999999"}],"gradientType":"radial","gradientRadial":"bottom center"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"24","bottom":"24","left":"24"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-5f19Sj","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"32"}},"rowGap":{"Desktop":{"unit":"px","point":"32"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-o97T5K","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-iwypDG","displayInline":true,"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-primary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-border-input"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"center"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-W6BnhS","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Something Wrong..."} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-shwiWJ","content":"\u003cspan id=\u0022guten-B3eeZF\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-ZL9n3F\u0022 id=\u0022guten-wLVG9u\u0022\u003ePage Not Found\u003c/span\u003e\u003c/span\u003e","type":1,"textAlign":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"96"}},"weight":"600","spacing":{"Desktop":"-0.02"},"font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"-1","top":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Tablet":"default","Mobile":"full"},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-wLVG9u","spanId":"guten-B3eeZF"}],"openChild":"guten-wLVG9u"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-SJGxR8","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"containsAnchorTag":false} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-CSAAOi","paragraph":"The page that you are looking for is missing. Please check your url again or back to the homepage","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"424"},"Mobile":{"unit":"px"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/button {"elementId":"guten-I0WRY7","content":"Back To Home","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"22","bottom":"16","left":"22"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"color":{"r":72,"g":185,"b":233,"a":0.12},"vertical":"0","horizontal":"0","spread":"5"},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTYxLjcgMTY5LjRsMTAxLjUgMjc4QzkyLjIgNDEzIDQzLjMgMzQwLjIgNDMuMyAyNTZjMC0zMC45IDYuNi02MC4xIDE4LjQtODYuNnptMzM3LjkgNzUuOWMwLTI2LjMtOS40LTQ0LjUtMTcuNS01OC43LTEwLjgtMTcuNS0yMC45LTMyLjQtMjAuOS00OS45IDAtMTkuNiAxNC44LTM3LjggMzUuNy0zNy44LjkgMCAxLjguMSAyLjguMi0zNy45LTM0LjctODguMy01NS45LTE0My43LTU1LjktNzQuMyAwLTEzOS43IDM4LjEtMTc3LjggOTUuOSA1IC4yIDkuNy4zIDEzLjcuMyAyMi4yIDAgNTYuNy0yLjcgNTYuNy0yLjcgMTEuNS0uNyAxMi44IDE2LjIgMS40IDE3LjUgMCAwLTExLjUgMS4zLTI0LjMgMmw3Ny41IDIzMC40TDI0OS44IDI0N2wtMzMuMS05MC44Yy0xMS41LS43LTIyLjMtMi0yMi4zLTItMTEuNS0uNy0xMC4xLTE4LjIgMS4zLTE3LjUgMCAwIDM1LjEgMi43IDU2IDIuNyAyMi4yIDAgNTYuNy0yLjcgNTYuNy0yLjcgMTEuNS0uNyAxMi44IDE2LjIgMS40IDE3LjUgMCAwLTExLjUgMS4zLTI0LjMgMmw3Ni45IDIyOC43IDIxLjItNzAuOWM5LTI5LjQgMTYtNTAuNSAxNi02OC43em0tMTM5LjkgMjkuM2wtNjMuOCAxODUuNWMxOS4xIDUuNiAzOS4yIDguNyA2MC4xIDguNyAyNC44IDAgNDguNS00LjMgNzAuNi0xMi4xLS42LS45LTEuMS0xLjktMS41LTIuOWwtNjUuNC0xNzkuMnptMTgzLTEyMC43Yy45IDYuOCAxLjQgMTQgMS40IDIxLjkgMCAyMS42LTQgNDUuOC0xNi4yIDc2LjJsLTY1IDE4Ny45QzQyNi4yIDQwMyA0NjguNyAzMzQuNSA0NjguNyAyNTZjMC0zNy05LjQtNzEuOC0yNi0xMDIuMXpNNTA0IDI1NmMwIDEzNi44LTExMS4zIDI0OC0yNDggMjQ4QzExOS4yIDUwNCA4IDM5Mi43IDggMjU2IDggMTE5LjIgMTE5LjIgOCAyNTYgOGMxMzYuNyAwIDI0OCAxMTEuMiAyNDggMjQ4em0tMTEuNCAwYzAtMTMwLjUtMTA2LjItMjM2LjYtMjM2LjYtMjM2LjZDMTI1LjUgMTkuNCAxOS40IDEyNS41IDE5LjQgMjU2UzEyNS42IDQ5Mi42IDI1NiA0OTIuNmMxMzAuNSAwIDIzNi42LTEwNi4xIDIzNi42LTIzNi42eiIvPjwvc3ZnPg==","color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"ariaLabel":"button to get started"} /-->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-54TNTj","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-WmWfEN","displayInline":true,"spaceBetween":{"Desktop":"18"},"alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-white"},"textColorHover":{"type":"variable","id":"gv-color-dark-text-secondary"},"textTypography":{"type":"variable","id":"gv-font-button-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"14"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vidV2j","url":"#","hasGlobalLink":true,"icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","hideIcon":true,"text":"Home","margin":{"Mobile":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"4","left":"0"}}}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Azvgq8","url":"#","hasGlobalLink":true,"icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","hideIcon":true,"text":"Services","margin":{"Mobile":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"4","left":"0"}}}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-5wWQOy","url":"#","hasGlobalLink":true,"icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","hideIcon":true,"text":"Projects","margin":{"Mobile":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"4","left":"0"}}}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-fL2jNs","url":"#","hasGlobalLink":true,"icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","hideIcon":true,"text":"Privacy Policy","margin":{"Mobile":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"4","left":"0"}}}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-iY9k2g","url":"#","hasGlobalLink":true,"icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","hideIcon":true,"text":"Terms \u0026 Condition","margin":{"Mobile":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"4","left":"0"}}}} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-wFKGRH","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"typography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"14"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-dark-text-primary"},"linkColorHover":{"type":"variable","id":"gv-color-dark-text-secondary"}} -->
<!-- wp:paragraph -->
<p>Copyright 2026. Built with <a href="#">Gutenverse</a> Tech Consultant Theme</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '',
	'is_sync' => false,
);
