<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory Projects Gutenverse List', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-pAWkrJ","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Tablet":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"flexDirection":{"Desktop":"row"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"}},"flexWrap":{"Desktop":"wrap"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"24","bottom":"160","left":"24"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-PwNbIu","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"column","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"},"image":{"Desktop":{"id":131,"image":"{image|other|35|url}","width":34,"height":34,"altOriginal":""}},"position":{"Desktop":"custom","Mobile":"bottom center"},"yposition":{"Desktop":{"unit":"px"}},"xposition":{"Desktop":{"unit":"px","point":"10"}},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"0"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(35, 35, 35, 0.88)","opacity":0.88,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(35, 35, 35, 1)","active":true,"opacity":1,"id":2,"offset":"0.32"}],"gradientType":"linear","gradientAngle":215},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"borderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Wb2otr","imgSrc":{"media":{"imageId":"24","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|24|url}","orientation":"landscape"},"medium":{"height":250,"width":300,"url":"{image|other|24|url}","orientation":"landscape"},"full":{"url":"{image|other|24|url}","height":528,"width":633,"orientation":"landscape"}}},"size":"full","id":"{image|case1|24|id}","image":"{image|case1|24|url}"},"altType":"original","altOriginal":"tecvisory project 01","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"320"},"Mobile":{"unit":"px","point":"208"},"Tablet":{"unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-MjBHZm","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"justifyContent":{"Desktop":"space-between"},"alignItems":{"Desktop":"flex-start"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"32","right":"32","bottom":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-2UCrTu","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-lMX2tj","displayInline":true,"alignList":{"Desktop":null},"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-K1juY4","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Projects"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-acOblL","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003e\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eEnterprise System Automation\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"left"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px"}},"spacing":{"Desktop":"-0.02"},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-VEvy6Y","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":""}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-Ky34uJ","paragraph":"Automated core business workflows for a regional logistics company, reducing manual processing time by 74% and cutting operational costs significantly.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-XNYxk3","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row","Mobile":"row"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"flexWrap":{"Mobile":"wrap"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Ij1Q2K","titleTag":"h3","text":"Type","focusText":"","subText":"Infrastructure","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-S1jFyS","titleTag":"h3","text":"Year","focusText":"","subText":"2026","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-3a2KAe","content":"","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"color":{"r":72,"g":185,"b":233,"a":0.12},"vertical":"0","horizontal":"0","spread":"5"},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconSize":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Desktop":"inline","Mobile":"full"},"ariaLabel":"button to get started","flexSize":{"Desktop":""}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-PRnUGi","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"column","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"},"image":{"Desktop":{"id":131,"image":"{image|other|35|url}","width":34,"height":34,"altOriginal":""}},"position":{"Desktop":"custom","Mobile":"bottom center"},"yposition":{"Desktop":{"unit":"px"}},"xposition":{"Desktop":{"unit":"px","point":"10"}},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"0"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(35, 35, 35, 0.88)","opacity":0.88,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(35, 35, 35, 1)","active":true,"opacity":1,"id":2,"offset":"0.32"}],"gradientType":"linear","gradientAngle":215},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"borderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Exw25O","imgSrc":{"media":{"imageId":"25","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|25|url}","orientation":"landscape"},"medium":{"height":250,"width":300,"url":"{image|other|25|url}","orientation":"landscape"},"full":{"url":"{image|other|25|url}","height":528,"width":633,"orientation":"landscape"}}},"size":"full","id":"{image|case1|25|id}","image":"{image|case1|25|url}"},"altType":"original","altOriginal":"tecvisory project 02","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"320"},"Mobile":{"unit":"px","point":"208"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-ECH8JG","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"justifyContent":{"Desktop":"space-between"},"alignItems":{"Desktop":"flex-start"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"32","right":"32","bottom":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-7ODtEv","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-7CqjV0","displayInline":true,"alignList":{"Desktop":null},"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-gLvXBX","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Projects"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-2Bkg7a","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003e\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eCloud Migration for Startup\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"left"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px"}},"spacing":{"Desktop":"-0.02"},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-fJvfQ4","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":""}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-Wh5M0G","paragraph":"Migrated a growing fintech platform from on-premise servers to a fully managed AWS environment - improving uptime to 99.9% and reducing infrastructure spend.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-N8RyfI","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row","Mobile":"row"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"flexWrap":{"Mobile":"wrap"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-fyBXC4","titleTag":"h3","text":"Type","focusText":"","subText":"Cloud","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-WSDuVQ","titleTag":"h3","text":"Year","focusText":"","subText":"2026","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-GeOFLy","content":"","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"color":{"r":72,"g":185,"b":233,"a":0.12},"vertical":"0","horizontal":"0","spread":"5"},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconSize":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Desktop":"inline","Mobile":"full"},"ariaLabel":"button to get started","flexSize":{"Desktop":""}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-0O1fnu","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"column","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"},"image":{"Desktop":{"id":131,"image":"{image|other|35|url}","width":34,"height":34,"altOriginal":""}},"position":{"Desktop":"custom","Mobile":"bottom center"},"yposition":{"Desktop":{"unit":"px"}},"xposition":{"Desktop":{"unit":"px","point":"10"}},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"0"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(35, 35, 35, 0.88)","opacity":0.88,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(35, 35, 35, 1)","active":true,"opacity":1,"id":2,"offset":"0.32"}],"gradientType":"linear","gradientAngle":215},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"borderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Ohalhf","imgSrc":{"media":{"imageId":"26","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|26|url}","orientation":"landscape"},"medium":{"height":250,"width":300,"url":"{image|other|26|url}","orientation":"landscape"},"full":{"url":"{image|other|26|url}","height":528,"width":633,"orientation":"landscape"}}},"size":"full","id":"{image|case1|26|id}","image":"{image|case1|26|url}"},"altType":"original","altOriginal":"tecvisory project 03","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"320"},"Mobile":{"unit":"px","point":"208"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-40LFDS","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"justifyContent":{"Desktop":"flex-start"},"alignItems":{"Desktop":"flex-start"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"32","right":"32","bottom":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-Ngf7eP","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-lykn5c","displayInline":true,"alignList":{"Desktop":null},"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-CLjuVo","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Projects"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-9AKTdg","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003e\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eSecurity Overhaul for Retail Chain\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"left"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px"}},"spacing":{"Desktop":"-0.02"},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-tWxRPQ","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":""}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-BWA1Z4","paragraph":"Conducted a full security audit and implemented a zero-trust architecture for a national retail chain with 50+ branches - passing ISO 27001 certification within 6 months.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-n1LBB5","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-FXhHEz","titleTag":"h3","text":"Type","focusText":"","subText":"Security","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-mv7Ov9","titleTag":"h3","text":"Year","focusText":"","subText":"2026","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-US5AF7","content":"","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"color":{"r":72,"g":185,"b":233,"a":0.12},"vertical":"0","horizontal":"0","spread":"5"},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconSize":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Desktop":"inline","Mobile":"full"},"ariaLabel":"button to get started","flexSize":{"Desktop":""}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-FacmKi","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"column","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"},"image":{"Desktop":{"id":131,"image":"{image|other|35|url}","width":34,"height":34,"altOriginal":""}},"position":{"Desktop":"custom","Mobile":"bottom center"},"yposition":{"Desktop":{"unit":"px"}},"xposition":{"Desktop":{"unit":"px","point":"10"}},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"0"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(35, 35, 35, 0.88)","opacity":0.88,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(35, 35, 35, 1)","active":true,"opacity":1,"id":2,"offset":"0.32"}],"gradientType":"linear","gradientAngle":215},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"borderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-3PPjlI","imgSrc":{"media":{"imageId":"27","sizes":{"thumbnail":{"height":150,"width":150,"url":"{image|other|27|url}","orientation":"landscape"},"medium":{"height":250,"width":300,"url":"{image|other|27|url}","orientation":"landscape"},"full":{"url":"{image|other|27|url}","height":528,"width":633,"orientation":"landscape"}}},"size":"full","id":"{image|case1|27|id}","image":"{image|case1|27|url}"},"altType":"original","altOriginal":"tecvisory project 04","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"1000"},"Mobile":{"unit":"px"}},"height":{"Desktop":{"unit":"px","point":"320"},"Mobile":{"unit":"px","point":"208"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"imageFit":{"Desktop":"cover"},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/container {"elementId":"guten-qgEa9k","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"justifyContent":{"Desktop":"flex-start"},"alignItems":{"Desktop":"flex-start"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px"}},"flexSize":{"Desktop":"grow"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"32","right":"32","bottom":"32","left":"32"}},"Mobile":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"positioningType":{"Desktop":"full","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"48"},"Tablet":{"unit":"px"}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-IpBz4C","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-GbA8Fp","displayInline":true,"alignList":{"Desktop":null},"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"2"},"iconSize":{"Desktop":"8"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"textIndent":{"Desktop":"6"},"textTypography":{"type":"variable","id":"gv-font-subheading","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"12"}},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"10","bottom":"6","left":"10"}}},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"px"}},"flexAlignSelf":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-pFC8Y4","icon":"fas fa-star","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxNi45IDE4QzMxMS42IDcgMzAwLjQgMCAyODguMSAwcy0yMy40IDctMjguOCAxOEwxOTUgMTUwLjMgNTEuNCAxNzEuNWMtMTIgMS44LTIyIDEwLjItMjUuNyAyMS43cy0uNyAyNC4yIDcuOSAzMi43TDEzNy44IDMyOSAxMTMuMiA0NzQuN2MtMiAxMiAzIDI0LjIgMTIuOSAzMS4zczIzIDggMzMuOCAyLjNsMTI4LjMtNjguNSAxMjguMyA2OC41YzEwLjggNS43IDIzLjkgNC45IDMzLjgtMi4zczE0LjktMTkuMyAxMi45LTMxLjNMNDM4LjUgMzI5IDU0Mi43IDIyNS45YzguNi04LjUgMTEuNy0yMS4yIDcuOS0zMi43cy0xMy43LTE5LjktMjUuNy0yMS43TDM4MS4yIDE1MC4zIDMxNi45IDE4eiIvPjwvc3ZnPg==","hideIcon":true,"text":"Projects"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/heading {"elementId":"guten-Ei5Xlc","content":"\u003cspan id=\u0022guten-PJ7WmB\u0022\u003e\u003cspan class=\u0022guten-text-highlight guten-YhdUBb\u0022 id=\u0022guten-EfTihj\u0022\u003eDigital Migration for Mid-Sized Company\u003c/span\u003e\u003c/span\u003e","textAlign":{"Desktop":"left"},"typography":{"type":"variable","id":"gv-font-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px"}},"spacing":{"Desktop":"-0.02"},"weight":"600","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textChilds":[{"color":[],"colorHover":[],"typography":[],"typographyHover":[],"textClip":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(153, 153, 153, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"170"},"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-EfTihj","spanId":"guten-PJ7WmB","_key":"fNQVbd"}],"openChild":"guten-EfTihj"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-4ydMcr","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left"},"containsAnchorTag":false,"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":""}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-Zy35ay","paragraph":"We are transforming for a 300-employee that stuck with the legacy system. We replaced disconnected spreadsheets and manual workflows with an integrated ERP system.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-EpNQLk","mode":"content","containerWidth":{"Desktop":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px","point":"16"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Vd6LYl","titleTag":"h3","text":"Type","focusText":"","subText":"Migration","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-oezfIH","titleTag":"h3","text":"Year","focusText":"","subText":"2026","showLine":"none","mainColor":{"type":"variable","id":"gv-color-dark-text-placeholder"},"mainTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"focusTypography":{"lineHeight":{"Desktop":{"unit":"px"}}},"subColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Mobile":"custom"},"positioningWidth":{"Mobile":{"unit":"%","point":"44"}},"flexSize":{"Mobile":"grow"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-eHQIqA","content":"","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"color":{"r":72,"g":185,"b":233,"a":0.12},"vertical":"0","horizontal":"0","spread":"5"},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"showIcon":true,"icon":"gtn gtn-right-arrow-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconSize":{"Desktop":{"unit":"px"},"Mobile":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"8","left":"0"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"size":{"Desktop":{"unit":"px","point":"16"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"positioningType":{"Desktop":"inline","Mobile":"full"},"ariaLabel":"button to get started","flexSize":{"Desktop":""}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '{"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-project-01.webp":{"pattern":["{image|case1|24|url}","{image|case1|24|id}","{image|other|24|url}"],"alt_text":"tecvisory project 01"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-project-02.webp":{"pattern":["{image|case1|25|url}","{image|case1|25|id}","{image|other|25|url}"],"alt_text":"tecvisory project 02"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-project-03.webp":{"pattern":["{image|case1|26|url}","{image|case1|26|id}","{image|other|26|url}"],"alt_text":"tecvisory project 03"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/tecvisory-project-04.webp":{"pattern":["{image|case1|27|url}","{image|case1|27|id}","{image|other|27|url}"],"alt_text":"tecvisory project 04"},"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/standard-dot-grid-pattern.webp":{"pattern":["{image|other|35|url}"]}}',
	'is_sync' => false,
);
