<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory Home Gutenverse Features', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-QCByY1","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"row","Tablet":"column"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"24","bottom":"160","left":"24"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}}} -->
<!-- wp:gutenverse/container {"elementId":"guten-QbwTwX","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"},"delay":null}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-Fdsj1W","content":"Data-Driven Strategy","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"24"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}} /-->

<!-- wp:gutenverse/container {"elementId":"guten-fw6LMp","mode":"content","minHeight":{"Desktop":{"unit":"px","point":"160"}},"justifyContent":{"Desktop":"center"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"overflow":"hidden","background":{"type":"default","image":{"Desktop":{"id":16,"image":"{image|other|7|url}","width":60,"height":60,"altOriginal":""}},"position":{"Desktop":"center center"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"40"}},"color":{"type":"variable","id":"gv-color-black"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 0.84)","opacity":0.84,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"radial"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"backgroundEffect":{"type":"none","leftOrientation":{"Desktop":{"unit":"%","point":""}},"topOrientation":{"Desktop":{"unit":"%","point":""}},"effectSpeed":{"unit":"s","point":""},"backgroundEffectSize":{"Desktop":{"unit":"px","point":""}},"effectColor":"","backgroundEffectLoadOn":"pageLoad","hiddenOverflow":false,"opacity":{"Desktop":""},"effectQuantity":"","delayBackgroundEffect":"0"}} -->
<!-- wp:gutenverse/container {"elementId":"guten-4A7RY4","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"backgroundEffect":{"type":"ripple","leftOrientation":{"Desktop":{"unit":"%","point":"50"}},"topOrientation":{"Desktop":{"unit":"%","point":"50"}},"effectSpeed":{"unit":"s","point":"4"},"backgroundEffectSize":{"Desktop":{"unit":"px","point":"320"}},"backgroundEffectLoadOn":"pageLoad","effectColor":{"type":"variable","id":"gv-color-dark-primary"},"opacity":{"Desktop":"0.48"},"delayBackgroundEffect":"0","effectQuantity":"4","hiddenOverflow":false,"useContainerShape":false}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-NMbsEi","icon":"gtn gtn-th-list-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik00IDZ2MjBoMjR2LTIwek02IDhoNXY0aC01ek0xMyA4aDEzdjRoLTEzek02IDE0aDV2NGgtNXpNMTMgMTRoMTN2NGgtMTN6TTYgMjBoNXY0aC01ek0xMyAyMGgxM3Y0aC0xM3oiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"unit":"px","point":"40"}},"iconPadding":{"Desktop":"12"},"iconShape":"circle","background":{"type":"gradient","gradientColor":[{"color":"rgba(72, 185, 233, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(12, 138, 192, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-9I3oLK","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-xOjokR","paragraph":"We base every recommendation on your business data, market insights, and measurable KPIs.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-V2sxQr","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"},"delay":null}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-uDxfHp","content":"End-to-End Execution","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"24"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}} /-->

<!-- wp:gutenverse/container {"elementId":"guten-W4Dygq","mode":"content","minHeight":{"Desktop":{"unit":"px","point":"160"}},"justifyContent":{"Desktop":"center"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"overflow":"hidden","background":{"type":"default","image":{"Desktop":{"id":16,"image":"{image|other|7|url}","width":60,"height":60,"altOriginal":""}},"position":{"Desktop":"center center"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"40"}},"color":{"type":"variable","id":"gv-color-black"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 0.84)","opacity":0.84,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"radial"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"backgroundEffect":{"type":"none","leftOrientation":{"Desktop":{"unit":"%","point":""}},"topOrientation":{"Desktop":{"unit":"%","point":""}},"effectSpeed":{"unit":"s","point":""},"backgroundEffectSize":{"Desktop":{"unit":"px","point":""}},"effectColor":"","backgroundEffectLoadOn":"pageLoad","hiddenOverflow":false,"opacity":{"Desktop":""},"effectQuantity":"","delayBackgroundEffect":"0"}} -->
<!-- wp:gutenverse/container {"elementId":"guten-O6Aaxi","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"backgroundEffect":{"type":"ripple","leftOrientation":{"Desktop":{"unit":"%"}},"topOrientation":{"Desktop":{"unit":"%"}},"effectSpeed":{"unit":"s","point":"4"},"backgroundEffectSize":{"Desktop":{"unit":"px","point":"320"}},"backgroundEffectLoadOn":"pageLoad","effectColor":{"type":"variable","id":"gv-color-dark-primary"},"opacity":{"Desktop":"0.48"},"delayBackgroundEffect":"0","effectQuantity":"4","hiddenOverflow":false}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-YJtNyq","icon":"gtn gtn-clipboard-check-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xNiAyYy0xLjI1OCAwLTIuMTUyIDAuODkxLTIuNTk0IDJoLTguNDA2djI1aDIydi0yNWgtOC40MDZjLTAuNDQxLTEuMTA5LTEuMzM2LTItMi41OTQtMnpNMTYgNGMwLjU1NSAwIDEgMC40NDUgMSAxdjFoM3YyaC04di0yaDN2LTFjMC0wLjU1NSAwLjQ0NS0xIDEtMXpNNyA2aDN2NGgxMnYtNGgzdjIxaC0xOHpNMjEuMjgxIDEzLjI4MWwtNi4yODEgNi4yODEtMy4yODEtMy4yODEtMS40MzggMS40MzggNCA0IDAuNzE5IDAuNjg4IDAuNzE5LTAuNjg4IDctN3oiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"unit":"px","point":"40"}},"iconPadding":{"Desktop":"12"},"iconShape":"circle","background":{"type":"gradient","gradientColor":[{"color":"rgba(72, 185, 233, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(12, 138, 192, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ECidX7","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-zxKLqT","paragraph":"From planning to deployment, we stay with you through every phase - so nothing falls through the cracks.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/container {"elementId":"guten-AzZYhJ","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px","point":"16"}},"rowGap":{"Desktop":{"unit":"px","point":"16"}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"animation":{"type":{"Desktop":"none"},"delay":null}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-JOv6Pp","content":"Scalable Solutions","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"size":{"Desktop":{"unit":"px","point":"24"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}} /-->

<!-- wp:gutenverse/container {"elementId":"guten-OP9Ewl","mode":"content","minHeight":{"Desktop":{"unit":"px","point":"160"}},"justifyContent":{"Desktop":"center"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"overflow":"hidden","background":{"type":"default","image":{"Desktop":{"id":16,"image":"{image|other|7|url}","width":60,"height":60,"altOriginal":""}},"position":{"Desktop":"center center"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"40"}},"color":{"type":"variable","id":"gv-color-black"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(26, 26, 26, 0.84)","opacity":0.84,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"radial"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"backgroundEffect":{"type":"none","leftOrientation":{"Desktop":{"unit":"%","point":""}},"topOrientation":{"Desktop":{"unit":"%","point":""}},"effectSpeed":{"unit":"s","point":""},"backgroundEffectSize":{"Desktop":{"unit":"px","point":""}},"effectColor":"","backgroundEffectLoadOn":"pageLoad","hiddenOverflow":false,"opacity":{"Desktop":""},"effectQuantity":"","delayBackgroundEffect":"0"}} -->
<!-- wp:gutenverse/container {"elementId":"guten-94Rlu5","mode":"content","minHeight":{"Desktop":{"unit":"px"}},"columnGap":{"Desktop":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px"}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline"},"backgroundEffect":{"type":"ripple","leftOrientation":{"Desktop":{"unit":"%"}},"topOrientation":{"Desktop":{"unit":"%"}},"effectSpeed":{"unit":"s","point":"4"},"backgroundEffectSize":{"Desktop":{"unit":"px","point":"320"}},"backgroundEffectLoadOn":"pageLoad","effectColor":{"type":"variable","id":"gv-color-dark-primary"},"opacity":{"Desktop":"0.48"},"delayBackgroundEffect":"0","effectQuantity":"4","hiddenOverflow":false}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-Lj0dbr","icon":"gtn gtn-chalkboard-solid","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik01IDd2MTZoLTJ2MmgyNnYtMmgtMnYtMTZ6TTcgOWgxOHYxNGgtMTh6TTIxLjI4MSAxMi4yODFsLTQuMjgxIDQuMjgxLTMuMjgxLTMuMjgxLTAuNzE5LTAuNjg4LTAuNzE5IDAuNjg4LTMgMyAxLjQzOCAxLjQzOCAyLjI4MS0yLjI4MSAzLjI4MSAzLjI4MSAwLjcxOSAwLjY4OCAwLjcxOS0wLjY4OCA1LTV6TTIwIDIwbC0xIDEgMSAxaDR2LTJ6Ij48L3BhdGg+Cjwvc3ZnPgo=","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"unit":"px","point":"40"}},"iconPadding":{"Desktop":"12"},"iconShape":"circle","background":{"type":"gradient","gradientColor":[{"color":"rgba(72, 185, 233, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(12, 138, 192, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} /-->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-jTkhKQ","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"containsAnchorTag":false,"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"positioningType":{"Desktop":"full"},"flexSize":{"Desktop":"grow"}} -->
<!-- wp:gutenverse/text-paragraph {"elementId":"guten-61n7ZC","paragraph":"Our solutions grow with your business. We build systems designed for today and architected for tomorrow.","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"containsAnchorTag":false,"typography":{"type":"variable","id":"gv-font-text-hero","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"size":{"Desktop":{"unit":"px","point":"18"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"400"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"450"}}} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/container -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '{"https:\/\/fse.jegtheme.com\/tecvisory\/wp-content\/uploads\/sites\/142\/2026\/04\/pattern-diamond-dot.webp":{"pattern":["{image|other|7|url}"]}}',
	'is_sync' => false,
);
