<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Tecvisory Search Gutenverse Hero', 'tecvisory' ),
	'categories' => array( 'tecvisory-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/container {"elementId":"guten-6GpsXM","htmlTag":"section","mode":"content","containerLayout":"boxed","containerWidth":{"Desktop":{"unit":"px","point":"1248"},"Tablet":{"unit":"%","point":100},"Mobile":{"unit":"%","point":100}},"minHeight":{"Desktop":{"unit":"vh","point":""},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"flexDirection":{"Desktop":"column","Tablet":"column"},"justifyContent":{"Desktop":"space-between"},"alignItems":{"Desktop":"center"},"columnGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"rowGap":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"overflow":"hidden","background":{"type":"default","image":{"Desktop":{"id":16,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pattern-diamond-dot.webp","width":60,"height":60,"altOriginal":""}},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"px","point":"30"}}},"backgroundOverlay":{"type":"gradient","color":{"type":"variable","id":"gv-color-dark-background-primary"},"gradientColor":[{"color":"rgba(26, 26, 26, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(26, 26, 26, 0.9)","active":true,"opacity":0.9,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"1","padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"24","bottom":"40","left":"24"}},"Mobile":{"unit":"px","dimension":{"top":"100"}}}} -->
<!-- wp:gutenverse/search-result-title {"elementId":"guten-e5KtKx","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"gv-font-primary-alt","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"41"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600","spacing":{"Desktop":"-0.02","Tablet":"","Mobile":""}}} /-->

<!-- wp:gutenverse/search {"elementId":"guten-A5GcLg","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-dark-text-placeholder"}},"inputPlaceholder":"Search the article here","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"16","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}}},"inputWidth":{"Desktop":{"point":"320","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"15"}},"weight":"400","font":{"label":"DM Sans","value":"DM Sans","type":"google"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"6","bottom":"6","left":"6"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"inputBorderHover":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"inputBorderFocus":{"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-white"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-dark-background-primary"}},"alignContent":{"Desktop":"center"},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo="} -->
<!-- wp:gutenverse/button {"elementId":"guten-VlQjUI","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"16","bottom":"16","left":"16"}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-dark-secondary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBoxShadow":{"spread":"5","blur":"0","color":{"r":72,"g":185,"b":233,"a":0.07781559405940594}},"buttonBoxShadowHover":{"spread":"0","color":{"type":"variable","id":"gv-color-dark-primary"}},"typography":{"type":"variable","id":"gv-font-button-primary","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"15"}},"font":{"label":"DM Sans","value":"DM Sans","type":"google"},"weight":"600"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/container -->',
	'image_importer_ver' => '2.0.0',
	'images'      => '',
	'is_sync' => false,
);
